baseURL = 'https://fascinating-peony-9f7402.netlify.app'
languageCode = 'en-us'
title = 'BARC Retreat 2024'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "BARC Retreat "

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Servus!'
homeIntroContent = """

_Last Updated: 1st Oct 2024_

|         | Monday   | Tuesday            | Wednesday                          | Thursday                     | Friday                 |
|---------|----------|--------------------|------------------------------------|------------------------------|------------------------|
| **Morning** |          | Check-in 🏨 /  Workshop I📖 |  WoSh III: FOCS 📖 |         | Check-out 🏨  |
| **Afternoon** | 🚃 | Workshop II 📖    | Hiking@<a href="https://nordkette.com/en/">Nordkette</a>🚡                   | Day Trip:  <a href="https://www.wasserfaelle-krimml.at/">Krimmler Waterfalls</a>        |               |
| **Evening** | 🚃 | Dinner @DasMEI 🍽️| <a href="https://www.tiroler-abend.com/en/" title="Tiroler Abend">Tyroler Evening & Dining</a> 🇦🇹  | Drinks at the hotel Bar 🍻 |                        |

### Packing List ❤️
We have put together a packing list for you:
<details>
    <summary style="font-weight: bold">PACKING LIST</summary>
    <div style="font-style: italic">
    <ul>
<li>Valid passport</li>
<li>Please note that if your passport is issues by a non-EU country you must also be able to document your entry permit to the EU. Living and working in Denmark you should all be in possession of this visa already.</li>
<li>Tickets for your return travel (Lukas holds the tickets for the train ride to Innsbruck)</li>
<li>Driver’s license, student ID</li>
<li>Travel insurance card (during the retreat KU employees are covered by KU travel insurance) If you are employed elsewhere, please ensure valid travel insurance.</li>
<li>Backpack for daytrips</li>
<li>What you need for work: pen & paper, your laptop/tablet incl. charger, either printed or downloaded FOCS abstracts </li>
<li>Refillable water bottle</li>
<li>Phone and charger</li>
<li>Wallet incl. credit cards. If you are holding a KU Master card, please bring it!</li>
<li>Cash Euros as spending money during the train ride, the layover in Hamburg central station and for tipping as well as paying local tourist fees (only 2 Euro per person). </li>
<li>Clothes (You know what you need but maybe check the weather forecast for Innsbruck when packing.)</li>
<li>Lederhosen, if you have…</li>
<li>Raincoat</li>
<li>Shirts for dinners (It’s a rather upscale hotel and dressing nicely for the dinners is expected.)  </li>
<li>Pants suitable for hiking</li>
<li>Hiking boots and/or trail running shoes</li>
<li>BARC t-shirts </li>
<li>Swim wear (we are staying at a SPA hotel)</li>
<li>Scarves, hat, gloves (for hiking)</li>
<li>Toiletries and medication (if needed)</li>
<li>Sunglasses (and sunscreen for hiking)</li>
<li>Books/e-books/magazines of your choice for the train ride or spare time</li>
<li>Headphones</li>
<li>If you have one, you might consider bringing: a travel sized card or board game, a Bluetooth speaker (incl. charger)</li>
</ul>
    </div>
</details>


## Detailed Plan

### Monday, Oct 14th
_(For night-train enthusiasts only!)_

**13:26 - 18:06**: Trip to Hamburg HBF (Central Station).

**18:06 - 20:10**: Finding some food at Hamburg Central Station.

**Departing at 20:10**: Night-Train.

### Tuesday, Oct 15th
_The Scientific Day_

**09:15**: Arrival in Innsbruck HBF.

**09:30 - 10:30**: Starting the day with a coffee at <a href="https://www.wilten-ibk.at/">Cafe Wilten</a>. Don't overeat! Schnitzel in 2h!

**10:30 - 10:50**: Transfer to our <a href="https://dasmei.at" title="Das MEI">hotel</a>. Not all rooms migh be available by the time of arrival, but we get a room to store our luggage.

**11:00 - 12:00**: _Scientific Session I hosted by Rasmus_ 
<details>
    <summary style="font-weight: bold">How to Pitch Your Research</summary>
    <div style="font-style: italic">An important part of academic training is learning to communicate effectively to other researchers in the peer community. However, sometimes you need to communicate to someone outside of the peer community, for example: writing a grant application, talking to a journalist, or explaining your research to a potential employer/collaborator with a different educational background. We will discuss some common pitfalls in such endeavors and talk about how you may practice pitching your research by using a large language model. Finally, we work in small groups on concrete case studies.</div>
</details>

**12:00 - 13:00**: Lunchbreak at our hotel. 
Traditional _Wiener Schnitzel_ has already been preordered for the non vegetarians and for our vegetarians I was told that "[their] second kitchen-chef can provide delicous veggy asian food".

**13:30 - 13:45**: _Anne_.

**13:45 - 15:00**: _Scientific Session II hosted by Amir_.
<details>
    <summary style="font-weight: bold; text-decoration: green wavy underline">Definitions.</summary>
    <div> Something about... definitions? Ask Amir ...</div>
</details>

**15:00 - 17:30**: Official check-in (SPA opens 16:00).

**From 18:00**: Dinner at our hotel.

### Wednesday, Oct 16th
_The Hiking Day_

**07:00 - 09:30**: Breakfast at the hotel.

**09:30 - 11:45**: _Scientific Session III: **FOCS Proceedings** by Mikkel T feat. a talk by Tuukka!_
Accepted papers <a href="https://focs.computer.org/2024/accepted-papers-for-focs-2024/">here</a>

**12:30 - 13:00**: Transfer to <a href="https://nordkette.com/">Nordkettenbahn</a>, taking the gondola up together. 
_As october has very unstable weather condition: Make sure to bring good clothes._

**13:30 - 14:30**: Restaurant <a href="https://seegrube.at/">Seegrube</a> on top of the mountain.

**14:30 - 19:00**: Free time + Hiking

**19:45 - 22:00** <a href="https://www.tiroler-abend.com/">Tiroler Abend</a> (Tyrolian Evening), Shuttlebus picking us up from the hotel at 19:45.
Besides a crash course in alpine culture, we will get a traditional three course menu.

### Thursday, Oct 17th
_The "Trip-To-Krimml-Day"_

**07:00 - 09:30**: Breakfast at our hotel - for later: madpakke / lunchbox to-go. Dress for an active day and according to the weather. 

**09:45 - 20:00**: Daytrip. We will visit some very famous waterfalls, called <a href="https://www.wasserfaelle-krimml.at/">Die Krimmler Wasserfälle</a>. 
After an approximately 2h panorama sightseening tour through Austria, we will have some hours to hike around the waterfalls.
We will get some dinner at <a href="https://www.schoenmoos-alm.at/en/">Schönmoos Alm</a> at 17:00.
There's gonna be cheese. 
A lot of cheese. 🧀🧀🧀

**From 20:00**: Free-Time & some drinks at our hotel.

### Friday, Oct 18th

**07:00 - 10:00**: Breakfast at our Hotel.

**10:00 - 11:00**: Short feedback session and check-out.

# Travel Information

* **Journey Back must be booked individually, because some people might stay a bit longer**. If you like to to take the night train back, you can book it here: <a href="https://www.nightjet.com/en/#/home" title="ÖBB Nightjet">ÖBB Nightjet</a>.
* We booked the Night Train from Hamburg to Innsbruck for those 16 people that have signed-up
* We will take this connection:  **Copenhagen Hovedbanegården --> Hamburg HBF -> Innsbruck HBF**, 14/10/2024 at 8:10pm – Arrival on 15/10/2024 at 9:14am

## Our Hotel

* We are going to stay in <a href="https://dasmei.at" title="Das MEI">DasMEI****</a> in Innsbruck. 
* The adress is _Hotel dasMEI****_, Natterer Str. 20-22, 6162 Mutters | Austria
* We will have a a private conference room, where we can hold our proceedings session

* **Check-In Tuesday**: from 15:00 - **Check-Out Friday**: Until 11:00 
* **Breakfast**: 07:30 - 10:30
* **SPA Opening**: 16:00 bis 21:00. Please respect the <a href="https://allabouttirol.com/nude-sauna-guide-austria/" title="Etiqeutte">sauna etiquette</a> in Austria. 
Nudity is expected **inside** the sauna, but you will get a bathrope for the common areas.  

<img src="Mountain.png" alt="Girl in a jacket">

         o o o o o o o . . .   _____________________ _____=====_||____
       o      _____           ||                   | |               |
     .][__n_n_|DD[  ====_____  |                   | |               |
    >(________|__|_[_________]_|___________________|_|_______________|
    _/oo OOOOO oo`  ooo   ooo  'o!o!o         o!o!o` 'o!o       o!o`
    -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+--+-+-+-+-+-+-+-+-+-+-+-+-+-+-
            
"""
# Add emergency contacts

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/user/"

#[[params.social]]
#name = "medium"
#url = "https://medium.com/@user"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "posts"
#url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highligth on code blocks
[markup]
    [markup.highlight]
     style = 'algol'
 [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
