baseURL = 'https://fascinating-peony-9f7402.netlify.app'
languageCode = 'de-de'
title = 'BARC Retreat'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Planning our Retreat in Austria"

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Servus!'
homeIntroContent = """
This page summarized some information for our Retreat in Austria! 

# Schedule

|         | Monday   | Tuesday            | Wednesday                          | Thursday                     | Friday                 |
|---------|----------|--------------------|------------------------------------|------------------------------|------------------------|
| 8-13  |          | Arrival, Check-In  | Breakfast + FOCS Proceedings (1/2) |  Grimmler Wasserfälle        | Free, Time for packing |
| 13-17 | (Travel) | (Workshop?), SPA   | Hiking@Nordkette                   |  Grimmler Wasserfälle        |  (Travel)              |
| 17-00 | (Travel) | Dinner at TBD, SPA | Evening Dinner in the Hotel + SPA  | Tyroler Evening incl. Dining |                        |


# Travel Information

* IMPORTANT!! **Journey Back must be booked individually, because some people might stay a bit longer**
* We booked the Night Train from Hamburg to Innsbruck for those 16 people that have signed-up
* We will take  this connection: Hamburg HBF -> Innsbruck HBF // 14/10/2024 at 8:10pm – Arrival on 15/10/2024 at 9:14am

# The Hotel

* We are going to stay in ![DasMEI](https://dasmei.at/) in Innsbruck.
The adress is _Hotel dasMEI****_, Natterer Str. 20-22, 6162 Mutters | Austria
It has a very nice SPA area and breakfast is served at xxxx.
* Breakfast: 7:30am - 10:30am
* SPA Opening: 4pm bis 9pm

"""

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/user/"

#[[params.social]]
#name = "medium"
#url = "https://medium.com/@user"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "posts"
#url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"