baseURL = 'https://fascinating-peony-9f7402.netlify.app'
languageCode = 'en-us'
title = 'BARC Retreat 2024'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "BARC Retreat "

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Servus!'
homeIntroContent = """


|         | Monday   | Tuesday            | Wednesday                          | Thursday                     | Friday                 |
|---------|----------|--------------------|------------------------------------|------------------------------|------------------------|
| **Morning** |          | Check-in 🏨 /  _Workshop I_📖 |  _WoSh III: FOCS_ 📖 |         | Check-out 🏨  |
| **Afternoon** | 🚃 | _Workshop II_ 📖    | Hiking@<a href="https://nordkette.com/en/">Nordkette</a>🚡                   | Day Trip:  <a href="https://www.wasserfaelle-krimml.at/">Grimmler Waterfalls</a>        |               |
| **Evening** | 🚃 | Dinner in [TBA] 🍽️| <a href="https://www.tiroler-abend.com/en/" title="Tiroler Abend">Tyroler Evening & Dining</a> 🇦🇹  | Drinks at the hotel Bar 🍻 |                        |


## Detailed Plan

**(Still Preliminary!)**

### Monday, Oct 14th
_(For night-train enthusiasts only!)_

**13:26 - 18:06**: Trip to Hamburg HBF (Central Station).

**18:06 - 20:10**: Finding some Food at Hamburg Central Station.

**Departing at 20:10**: Night-Train.

### Tuesday, Oct 15th
_The Scientific Day_

**09:30**: Arrival in Innsbruck HBF.

**09:30 - 10:30**: Starting the day with a coffee.

**10:30 - 11:00**: Transfer to our Hotel.

**11:00 - 12:00**: _Scientific Session I by [TBD]_.

**12:00 - 13:00**: Lunchbreak (Traditional _Schnitzel_ has already been preordered for the non vegetarians and for our vegetarians I was told tha: "Our second kitchen-chef can provide delicous veggy asian food").

**13:30 - 15:00**: _Scientific Session II by [Amir]_.

**15:00 - 17:30**: Official check-in (SPA opens 16:00).

**From 18:00**: Dinner at [TBD]. Maybe a bar in the center.

### Wednesday, Oct 16th
_The Hiking Day_

**07:00 - 09:30**: Breakfast at the hotel.

**09:30 - 11:30**: _Scientific Session III: **FOCS Proceedings** by Mikkel T_:

**11:30 - 13:00**: Transfer to Nordkettenbahn, Take a gondola.

**13:00 - 14:00**: Restaurant on top of the mountain.

**14:00 - 19:00**: Free, our suggestion: take a longer hike (some gpx's being posted later on)

**20:00 - 22:00** Tiroler evening incl. transfer from our hotel.

### Thursday, Oct 17th
_The "Trip-To-Grimml-Day"_

**07:00 - 09:30**: Breakfast at our hotel - for later: madpakke / lunchbox to-go

**09:45 - 20:00**: Daytrip to Grimmler Wasserfälle: We will visit some very famous waterfalls, called <a href="https://www.wasserfaelle-krimml.at/">Die Grimmler Wasserfälle</a>. 
After an approximately 2h panorama sightseening tour through austria, we will have some hours to hike around the waterfalls.

**From 20:00**: Free-Time & some drinks at our hotel.

### Friday, Oct 18th

**07:00 - 10:00**: Breakfast at our Hotel.

**10:00 - 11:00**: short feedback session and check-out.


# Travel Information

* **Journey Back must be booked individually, because some people might stay a bit longer**. If you like to to take the night train back, you can book it here: <a href="https://www.nightjet.com/en/#/home" title="ÖBB Nightjet">ÖBB Nightjet</a>.
* We booked the Night Train from Hamburg to Innsbruck for those 16 people that have signed-up
* We will take this connection:  **Copenhagen Hovedbanegården --> Hamburg HBF -> Innsbruck HBF**, 14/10/2024 at 8:10pm – Arrival on 15/10/2024 at 9:14am

## Our Hotel

* We are going to stay in <a href="https://dasmei.at" title="Das MEI">DasMEI****</a> in Innsbruck. 
* The adress is _Hotel dasMEI****_, Natterer Str. 20-22, 6162 Mutters | Austria
* We will have a a private conference room, where we can hold our proceedings session

* **Check-In Tuesday**: from 15:00 - **Check-Out Friday**: Until 11:00 
* **Breakfast**: 7:30am - 10:30am
* **SPA Opening**: 4pm bis 9pm. But respect the SPA Etiquette in Austria / Germany.

<img src="Mountain.png" alt="Girl in a jacket">

         o o o o o o o . . .   _____________________ _____=====_||____
       o      _____           ||                   | |               |
     .][__n_n_|DD[  ====_____  |                   | |               |
    >(________|__|_[_________]_|___________________|_|_______________|
    _/oo OOOOO oo`  ooo   ooo  'o!o!o         o!o!o` 'o!o       o!o`
    -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+--+-+-+-+-+-+-+-+-+-+-+-+-+-+-
            
"""
# Add emergency contacts

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/user/"

#[[params.social]]
#name = "medium"
#url = "https://medium.com/@user"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "posts"
#url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highligth on code blocks
[markup]
    [markup.highlight]
     style = 'algol'
 [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
