baseURL = 'https://fascinating-peony-9f7402.netlify.app'
languageCode = 'en-us'
title = 'BARC Retreat 2025'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "BARC Retreat "

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = """
"""

homeIntroContent = """
<img src="BARC-Beach.png" alt="BARC Retreat 2025" />

_Last Updated: 2nd Sep 2025_

<b>When</b>: September 22 to 26, 2025 <br>
<b>Where</b>: <a href="https://enjoyresorts.dk/enjoy-resorts-roemoe/">Enjoy Resorts Rømø</a>
"""

homeContent = """

<div class="packing-list">
    <h3>Packing List ❤️</h3>
    <p>We have put together a packing list for you:</p>
    <details>
        <summary style="font-weight: bold">PACKING LIST</summary>
        <div>
        <ul>
        <li>Valid passport (on the boat trips we pass into German waters and a passport is mandatory to bring)<br>
        Please note that if your passport is issued by a non-EU country you must also be able to document your entry permit to the EU. Living and working in Denmark you should have this visa already, so don’t worry, just remember to bring it.</li>
        <li>Backpack for daytrips</li>
        <li>What you need for work: pen & paper, your laptop/tablet incl. charger, either printed or downloaded FOCS 2025 abstracts</li>
        <li>Refillable water bottle</li>
        <li>Phone and charger</li>
        <li>Wallet. If you are holding a KU Master card, please bring it!</li>
        <li>Your best lasagna recipe</li>
        <li>Clothes (You know what you need but maybe check the weather forecast for Rømø when packing.)</li>
        <li>Raincoat/wind proof jacket</li>
        <li>Swim wear and a towel for the beach (you cannot take hotel towels to the beach!)</li>
        <li>Scarf, hat (might get chilly on the boat rides)</li>
        <li>Toiletries and medication (as needed)</li>
        <li>Binoculars (if you have)</li>
        <li>Your favorite BARC shirts</li>
        <li>Table tennis bat (if you suffer from this inclination)</li>
        </ul>
        </div>
    </details>
</div>

## Plan for the houses
<div class="house-plan">
<table>
  <thead>
    <tr>
      <th>The Party House</th>
      <th>House 2</th>
      <th>House 3</th>
      <th>House 4</th>
      <th>House 5</th>
      <th>House 6</th>
      <th>House 7</th>
      <th>House 8</th>
      <th>House 9</th>
      <th>House 10</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Jacob Imola</td>
      <td>Hanzhi</td>
      <td>Mikkel Thorup</td>
      <td>Yassine</td>
      <td>Benjamin</td>
      <td>Prateek</td>
      <td>Florestan</td>
      <td>Hanwen</td>
      <td>Mikkel Abrahamsen</td>
      <td>Jacob Holm</td>
    </tr>
    <tr>
      <td>Mads</td>
      <td>Sia</td>
      <td>Rasmus</td>
      <td>Sophus</td>
      <td>Amik</td>
      <td>Tuukka</td>
      <td>Egor</td>
      <td>Shuyi</td>
      <td>Amir</td>
      <td>Stephen</td>
    </tr>
    <tr>
      <td>Ian</td>
      <td>Deborah</td>
      <td>Thore</td>
      <td>Christian</td>
      <td>Jack</td>
      <td>Srikant</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Anne</td>
      <td>Anders</td>
      <td>Duri</td>
      <td>Théo</td>
      <td>Nutan</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>
</div>

* The Party House will be the gathering point for social activities in the evenings.
* Every house has two bedrooms with each two beds. 
* In houses 2 – 6 two people share a room.
* In houses 7 – 10 each person has a room to themself.


<div></div>

    .-------------------------------------------------------------.
    '------..-------------..----------..----------..----------..--.|
    |       \\            ||          ||          ||          ||  ||
    |        \\           ||          ||          ||          ||  ||
    |    ..   ||  _    _  ||    _   _ || _    _   ||    _    _||  ||
    |    ||   || //   //  ||   //  // ||//   //   ||   //   //|| /||
    |_.------"''----------''----------''----------''----------''--'|
    |)|      |       |       |       |    |      mga|      ||==|  |
    | |      |  _-_  |       |       |    |  .-.    |      ||==| C|
    | |  __  |.'.-.' |   _   |   _   |    |.'.-.'.  |  __  | "__=='
    '---------'|( )|'----------------------'|( )|'----------""
                '-'                          '-'
"""

# Add emergency contacts

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

[params.schedule]
headers = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday"
]
rows = [
  [
    "<b>Meet</b> in the courtyard of Vibenshuset at 8:30",
    "<b>Morning dip</b> at the beach with Mads at 7:00 (optional) – meet at reception",
    "<b>Morning dip</b> at the beach with Mads at 7:00 (optional) – meet at reception",
    "<b>Morning dip</b> at the beach with Mads at 7:00 (optional) – meet at reception",
    "<b>Pack up and check out</b>, bring luggage to the reception for storage.<br><i>Leave houses neat and tidy, dishwashers and bins emptied!</i>"
  ],
  [
    "<b>Bus transport</b> (with breakfast) from Vibenshuset to Rømø<br><b>Departure at 9:00</b><br>Arrival at 13:30<br>We will be staying at:<br><i>Enjoy Resorts Rømø<br>Vestergade 31<br>6792 Rømø</i>",
    "<b>Breakfast</b> available 8:00 – 8:50",
    "<b>Breakfast</b> available 8:00 – 8:50",
    "<b>Breakfast</b> available 8:00 – 8:50",
    "<b>Breakfast</b> available 8:00 – 8:30<br>Departure from reception 8:40 to Havneby (15 min walk)"
  ],
  [
    "<b>Lunch</b> resort restaurant “Diget” 13:30",
    "<b>Academic Workshop</b> 9:00 – 12:30<br>Coffee break at 10:30<br>Meta discussions in smaller groups, collective presentations before lunch.<br><b>Lunch</b> resort restaurant “Diget” 12:30",
    "<b>Academic Workshop</b> 9:00 – 12:30<br>Coffee break at 10:30<br>FOCS proceedings<br><b>Lunch</b> resort restaurant “Diget” 12:30",
    "<b>Academic Workshop</b> 9:00 – 12:00<br>Coffee break at 10:30<br>FOCS proceedings and discussion of new research ideas<br><b>Bus pick-up</b> at hotel reception 12:10, transfer to Lakolk (15 min by chartered bus)<br><b>Lunch</b> at Café Fru Dax 12:30 – 13:30",
    "<b>Seal Safari</b> by boat at 9:00<br>Bring: Passport (!), windbreaker, warm clothing and binoculars<br>Back approx. 13:15<br>Return to hotel for lunch, 15 min walk<br><b>Quick lunch</b> resort restaurant “Diget” 13:30 – 14:15"
  ],
  [
    "<b>Check-in</b> 14:00 – 15:00",
    "<b>Exploring the Wadden Sea</b><br>Departure from reception at 13:30<br>Dress according to weather and expect walking for 2-3 hours.",
    "<b>Recreational time</b><br>Choose between:<br>Pool / wellness area until 16:00<br>Table tennis (at resort)<br>Golf (at own expense)<br>Rent a bike (tandems available!)<br>Walk in the area<br>If you can’t resist: do research",
    "<b>Cultural sightseeing</b><br>WWII bunker, highest point (19 m) and museum<br>13:30 – 15:30<br>Arrival back at resort approx. 15:45",
    "Retrieve your luggage and <b>board the bus</b> at 14:20"
  ],
  [
    "<b>Free time until dinner</b><br>(Pool and wellness area open extraordinarily until 17:00)",
    "<b>Black Sun excursion</b> (optional) 17:15 – 20:30<br>(pick-up at hotel)<br>Bring: Passport (!), windbreaker, warm clothing and binoculars",
    "<b>Cooking contest!</b> Every house must prepare a home-made lasagne to be ready at 19:00 at The Party House. Houses 7&8 as well as 9&10 team up. The Party House prepares dessert!",
    "<b>Free time until dinner</b>",
    "<b>Bus transport</b> with snacks and tea/coffee back to Vibenshuset.<br><b>Departure from resort 14:30</b><br>Brief stop at Fredericia approx. 16:15, arrival in Copenhagen approx. 19:30"
  ],
  [
    "<b>Dinner</b> at resort restaurant “Diget” 18:00<br><b>Hygge</b> and board games at the Party House",
    "<b>Dinner</b> at resort restaurant “Diget” 20:45",
    "<b>Dinner</b> at The Party House at 19:00<br>Lasagne showdown – which house wins?<br><b>Hygge</b> and board games at the Party House",
    "<b>Dinner</b> at resort restaurant “Diget” 18:00 – 19:00<br><b>BARC’n’Bowl</b> at hotel 19:00 – 21:00",
    ""
  ]
]

# Social icons
#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/user/"

#[[params.social]]
#name = "medium"
#url = "https://medium.com/@user"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "posts"
#url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highligth on code blocks
[markup]
    [markup.highlight]
     style = 'algol'
 [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"